### ISSUE TITLE
Error logging error due to invalid encoding

### ISSUE THREAD

**Issue by mook-as** [mailprocessing/mailprocessing#5]
Hi! I appear to be hitting an error decoding one of my messages, which is causing a different error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 478, in _download_headers_batched
    s = s.decode(c if c else "ascii")
UnicodeDecodeError: 'iso2022_jp' codec can't decode bytes in position 5-6: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/imapproc", line 11, in <module>
    load_entry_point('mailprocessing==1.2.6', 'console_scripts', 'imapproc')()
  File "/usr/lib/python3.6/site-packages/mailprocessing/cmd/imap.py", line 326, in main
    processor = ImapProcessor(rcfile, log_fp, **processor_kwargs)
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 114, in __init__
    self.set_folders(kwargs['folders'])
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 176, in set_folders
    self._cache_headers()
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 319, in _cache_headers
    self._cache_headers_file()
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 354, in _cache_headers_file
    self._cache_headers_memory()
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 339, in _cache_headers_memory
    folder, self.header_cache[folder]['uids'])
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 559, in _update_cache
    messages = self._download_headers_batched(folder, uids_download)
  File "/usr/lib/python3.6/site-packages/mailprocessing/processor/imap.py", line 482, in _download_headers_batched
    self._processor.log_error(
AttributeError: 'ImapProcessor' object has no attribute '_processor'
```
I see that there was code to attempt to handle the decoding issue,  but that is itself falling over.

imapproc 1.0.1 (from mailprocessing 1.2.6-lp151.6.1 from `obs://server:mail`; I understand you maintain the packages on OBS as well?).  Unfortunately I can't figure out which message is causing the issue, so moving it out of the way is a bit hard.

Thanks for imapproc!

**Comment by jgrassler** [comment]
> I see that there was code to attempt to handle the decoding issue,  but that is itself falling over.

Yes there is, and it what causes the problem. Here's a preliminary fix
(I will only be able to test next week, but feel free to try it
meanwhile):

https://github.com/mailprocessing/mailprocessing/commit/1372654239ec6823f3f6117ee88df9fa58f7f603

With that in place you should see at least the message's UID in the log.
You may encounter other problems at later stages, but less cross that
bridge when we get to it...

> imapproc 1.0.1

Oops. That I need to fix as well (`--version` should report the package
version, not the hardcoded "1.0.1" I've got in there).

> (from mailprocessing 1.2.6-lp151.6.1 from
> `obs://server:mail`; I understand you maintain the packages on OBS as
> well?).

Yes, I do. There's an update in the pipeline for dealing with Office365
as well that I haven't gotten around to fully testing, yet. I plan on
cutting a new release and updating the package next week to get that
out.

While I'm at it I'd like to include the above fix for this issue as
well. I'd appreciate if you could test it and check if it works for you.

> Unfortunately I can't figure out which message is causing the
> issue, so moving it out of the way is a bit hard.

The modified code from the commit above should do the trick. Let's hope
so. If it doesn't let me know and I'll take a closer look at the problem
next week. Thanks!

**Comment by mook-as** [comment]
Unfortunately, things seemed to have _magically_ fixed itself; I didn't end up moving or deleting any messages manually, but I can no longer see the error.  Sorry I couldn't be more helpful.

I'm not even sure what message would have been in iso-2022-jp… I do not find any relevant results grepping for `2022` in my Thunderbird maildir.

Thanks for the prompt response!
